# Generated by Django 5.2.7 on 2025-10-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student'), ('moderator', 'Moderator')], default='student', max_length=50),
        ),
    ]
