# Generated by Django 5.2.7 on 2025-10-05 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='creat_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default=datetime.date.today, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default=datetime.date.today, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=datetime.date.today, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
