services:
  backend_service:
    build: .
    env_file:
      - .env
    ports:
      - "8004:8000"
    depends_on:
      - postgres_service
      - dragonfly_service
    volumes:
      - .:/app

  postgres_service:
    image: postgres:alpine
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  minio_service:
    image: minio/minio:RELEASE.2024-07-16T23-46-41Z
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'

    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_DEFAULT_BUCKETS=${MINIO_DEFAULT_BUCKETS}
    command: server /data --console-address ":9001"

  dragonfly_service:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    container_name: dragonfly
    ports:
      - "6379:6379"


volumes:
  pg_data:
  minio_data:
    driver: local

