services:
  backend_service:
    build: .
    env_file:
      - .env
    ports:
      - "8004:8000"
    depends_on:
      - postgres_service


  postgres_service:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"