# Generated by Django 5.2.7 on 2025-10-18 02:47

import django.db.models.deletion
import django_ckeditor_5.fields
import main.models.base
import main.models.courses
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.UUIDField(db_default=main.models.base.GenRandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('name', models.CharField(max_length=155)),
            ],
            options={
                'verbose_name': 'Категория Блога',
                'verbose_name_plural': 'Категории Блога',
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Продолжительность в часах', max_digits=3, null=True, verbose_name='Продолжительность'),
        ),
        migrations.AlterField(
            model_name='course',
            name='preview_img',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.courses.course_upload_path, verbose_name='Эскиз'),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.UUIDField(db_default=main.models.base.GenRandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='blogs/%Y/%m/%d')),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
                ('archived', models.BooleanField(db_default=False)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blogs', to='main.blogcategory')),
            ],
            options={
                'verbose_name': 'Болг',
                'verbose_name_plural': 'Блоги',
            },
        ),
    ]
