# Generated by Django 5.2.7 on 2025-10-18 05:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_blogcategory_alter_course_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturecontent',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=155),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='course',
            name='subtitles',
        ),
        migrations.AlterField(
            model_name='course',
            name='topics',
            field=models.ManyToManyField(blank=True, help_text='Обзор связанных тем', related_name='courses', to='main.topic'),
        ),
        migrations.AlterField(
            model_name='lecturecontent',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_contents', to='main.lecture'),
        ),
        migrations.AddField(
            model_name='course',
            name='subtitles',
            field=models.ManyToManyField(related_name='courses_subtitles', to='main.language'),
        ),
    ]
