# Generated by Django 5.2.7 on 2025-10-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='requirements',
            field=models.JSONField(default=list, verbose_name='Требования'),
        ),
        migrations.AddField(
            model_name='course',
            name='target_audience',
            field=models.JSONField(default=list, verbose_name='Для кого этот курс'),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='total_course_count',
            field=models.PositiveIntegerField(blank=True, db_default=0, null=True),
        ),
    ]
