# Generated by Django 5.2.7 on 2025-10-22 13:55

import apps.edu.models.courses
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0002_course_requirements_course_target_audience_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturecontent',
            name='section',
            field=models.ForeignKey(default='5dfde3e4-9d2d-4f37-8bbc-138908c41c88', on_delete=django.db.models.deletion.CASCADE, to='edu.section'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'type': 'student'}, null=True, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL, verbose_name='Студенты'),
        ),
        migrations.AlterField(
            model_name='course',
            name='subtitles',
            field=models.ManyToManyField(blank=True, null=True, related_name='courses_subtitles', to='edu.language'),
        ),
        migrations.AlterField(
            model_name='lecturecontent',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.edu.models.courses.course_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['.jpg', 'jpeg', 'png', '.pdf', '.docx'])], verbose_name='Файл к уроку'),
        ),
        migrations.AlterField(
            model_name='lecturecontent',
            name='title',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
