# Generated by Django 5.2.7 on 2025-10-22 13:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0003_lecturecontent_section_alter_course_students_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'type': 'student'}, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL, verbose_name='Студенты'),
        ),
        migrations.AlterField(
            model_name='course',
            name='subtitles',
            field=models.ManyToManyField(blank=True, related_name='courses_subtitles', to='edu.language'),
        ),
    ]
